### ISSUE TITLE
setup.py build fail

### ISSUE THREAD

**Issue by frank-netizen** [jsommers/pytricia#13]
![image](https://cloud.githubusercontent.com/assets/9162161/25521497/6cf764c2-2c32-11e7-8371-20f1ccaa98b0.png)

when i build project，and this error throw。anyone know what？

**Comment by jsommers** [comment]
Pytricia hasn't been tested at all on any Windows systems, cygwin, etc., or otherwise.  The error message above comes about because Pytricia needs a standard C header file on UNIX-like systems which doesn't apparently exist in the mingw toolchain.  I can't comment any further than that since I am very much unfamiliar with mingw or doing any of this on windows.  Sorry.

I may consider supporting Windows systems in the future, but for now they're not supported at all.

**Comment by frank-netizen** [comment]
ok，thanks jsommers .
